export const POKEMON_LIST_LOADING = "POKEMON_LIST_LOADING";
export const POKEMON_LIST_SUCCESS = "POKEMON_LIST_SUCCESS";
export const POKEMON_LIST_FAIL = "POKEMON_LIST_FAIL";

export const POKEMON_MULTIPLE_LOADING = "POKEMON_MULTIPLE_LOADING";
export const POKEMON_MULTIPLE_SUCCESS = "POKEMON_MULTIPLE_SUCCESS";
export const POKEMON_MULTIPLE_FAIL = "POKEMON_MULTIPLE_FAIL";

export const POKEMON_IMAGE_LOADING = "POKEMON_IMAGE_LOADING";
export const POKEMON_IMAGE_SUCCESS = "POKEMON_IMAGE_SUCCESS";
export const POKEMON_IMAGE_FAIL = "POKEMON_IMAGE_FAIL";

export const POKEMON_MULTIPLE_SPECIES_LOADING = "POKEMON_MULTIPLE_SPECIES_LOADING";
export const POKEMON_MULTIPLE_SPECIES_SUCCESS = "POKEMON_MULTIPLE_SPECIES_SUCCESS";
export const POKEMON_MULTIPLE_SPECIES_FAIL = "POKEMON_MULTIPLE_SPECIES_FAIL";

export const POKEMON_URL_LOADING = "POKEMON_URL_LOADING";
export const POKEMON_URL_SUCCESS = "POKEMON_URL_SUCCESS";
export const POKEMON_URL_FAIL = "POKEMON_URL_FAIL";